apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codesage
resources:
  - namespace.yaml
  - qdrant.yaml
  - ollama.yaml
  - retrieval-service.yaml
  - gateway-api.yaml
  - ingress.yaml
